echo "#!/bin/bash" 
echo "echo '---------------------------------'" 
echo "echo 'Build successful! Hello from EC2!'" 
echo "echo 'Build was triggered by commit: $GIT_COMMIT'" 
echo "echo 'Job: $JOB_NAME, Build: $BUILD_NUMBER'"
echo "echo '---------------------------------'"
